spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: group-0
      key-deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      max-poll-records: 1000
    properties:
      schema.registry.url: ${SCHEMA_REGISTRY:http://localhost:8081}
      specific.avro.reader: true
    bootstrap-servers: ${BOOTSTRAP_SERVERS:http://localhost:9092}
  datasource:
    hikari:
      connection-timeout: 30000
      idle-timeout: 30000
      minimum-idle: 1
      max-lifetime: 270000
      auto-commit: false
      jdbc-url: ${JDBC_URL:jdbc:mysql://127.0.0.1:3306/kafka}
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: pa
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${JDBC_URL:jdbc:mysql://127.0.0.1:3306/kafka}
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.jdbc.time_zone: UTC
    database: mysql
  liquibase:
    enabled: true
    url: ${JDBC_URL:jdbc:mysql://mysql:3306/kafka}
    user: root
    password: pa
    driver-class-name: com.mysql.cj.jdbc.Driver
    change-log: classpath:changelog/db.changelog-master.xml
  application:
    name: consumer

app:
  kafka:
    topic: client-topic
  misc:
    tax-percent: ${TAX_PERCENT:10}
